spring:
  application:
    name: server-service
  datasource:
    url: jdbc:sqlite:data\nexara.db  # 数据库文件的路径
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    username: ""
    password: ""
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 8      # 最大连接数
          max-idle: 4        # 最大空闲连接
          min-idle: 1        # 最小空闲连接
          max-wait: 2000ms   # 连接池等待超时时间
      timeout: 5000ms        # 连接超时时间
  servlet:
    multipart:
      max-file-size: 20MB      # 单个文件
      max-request-size: 100MB   # 整个 multipart 请求

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名自动映射
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nexara.server.polo.model


knife4j:
  enable: true
  setting:
    language: zh-CN  # 中文界面
    enable-swagger-models: true  # 显示模型
    enable-document-manage: true  # 允许文档管理
    enable-version: true  # 显示版本号