version: "3.8"
services:
  java-service-2:
    build: "./backends/backend-1"
    image: "java-service-2:latest"
    ports:
      - "8082:8082" 
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082
      - JAVA_VERSION=21
    volumes:
      - "/tmp:/tmp"
    restart: "unless-stopped"